config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  get 'home/index'

  devise_for :users
  root to: 'tweets#index'

  get 'profile' => 'home#userlist'
  post 'profile' => 'home#follow_unfollow'

  resources :user do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :tweet, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets

  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def self.all_except(user)
    where.not(id: user)
  end

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/authentication.rb
module Authentication
    extend ActiveSupport::Concern

    def authenticated_user!
        if !user_signed_in?
            redirect_to new_user_session_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticated_user!
  include Authentication

  def index
  end

  def userlist
    @users = User.all_except(current_user)
    @user_followers = current_user.followers
    @user_following = current_user.following
    @type = [:following, :followers]
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :authenticated_user!
    include Authentication
    
    def create
        user = User.find(params[:followed_id])
        current_user.follow(user)
        redirect_to user
    end

    def destroy
        user = Relationship.find(params[:id]).followed
        current_user.unfollow(user)
        redirect_to user
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticated_user!
  include Authentication

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.reverse_order
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweet, :user_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticated_user!
  include Authentication
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @user_followers = ''
    @user_following = @user.following
    @type = [:following]
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @user_followers = @user.followers
    @user_following = ''
    @type = [:followers]
    render 'show_follow'
  end

  def show
    @user = User.find(params[:id])
    @user_followers = @user.followers
    @user_following = @user.following
    @type = [:following, :followers]
    render 'show_follow'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/application/_navigation.html.erb
<% navs = {
    Home: root_path,
    Profile: profile_path
    }
%>
<% total_navs = navs.count %>
<% i = 0 %>

<% navs.each do |key, value| %>
    <%= link_to  key.to_s.humanize, value %>
    <% i += 1 %>
    <%= :| if i < total_navs %>
<% end %>

<% if user_signed_in? %>
    <div class="right">
        <b>Hello <%= current_user.email %></b> | 
        <%= link_to  "Log Out", destroy_user_session_path, {class: :red, method: :delete, data: { confirm: 'Are you sure?' } } %>
    </div>
<% end %>

app/views/application/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/userlist.html.erb
<table border='1' cellpadding='5' cellspacing='1'>
    <thead>
        <tr>
            <th>S.No.</th>
            <th>Email</th>
            <th>Follow / Un-Follow</th>
        </tr>
    </thead>
    <tbody>
        <% i = 0 %>
        <% @users.each do | user | %>
            <% @user = user %>
            <tr>
                <td><%= i += 1 %></td>
                <td><%= user.try(:email) %></td>
                <td>
                    <div id="follow_form">
                        <% if current_user.following?(@user) %>
                            <%= render 'unfollow' %>
                        <% else %>
                            <%= render 'follow' %>
                        <% end %>
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<% @user = current_user %>
<%= render :file => 'user/show_follow' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "navigation" %>
    <hr>
    <p class="notice green"><%= notice %></p>
    <p class="alert red"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a> | 
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a> | 
  <a href="<%= user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count + @user.following.count %>
    </strong>
    followers
  </a>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tweet %>
    <%= form.text_area :tweet, id: :tweet_tweet %>
  </div>

  <%= form.hidden_field :user_id, id: :tweet_user_id, :value => current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p> 
<%
=end%>

<h1>Tweets</h1>


<ul class="tweets">

    <% @tweets.each do |tweet| %>
      <li>
        <%= tweet.tweet %>
        <b> - <%= link_to tweet.user.email, tweet, {class: :user_profile} %></b>
      </li>
    <% end %>
</ul>
<%
=begin%>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.tweet %></td>
        <td><%= tweet.user.email %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
    <% end %>
<%
=end%>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p> 
<%
=end%>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%
=begin%>
 <p>
  <strong>User:</strong>
  <%= @tweet.user %>
</p> 
<%
=end%>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/user/show_follow.html.erb
<h3>User - <%= @user.email %></h3>
<%= render 'partials/stats' %>
<br>
<b>Total Tweets:</b> <%= @user.tweets.count %>
<hr>
<div class="row">
  <% if @type.include? :followers %>
    <div class="col-4">
      <h3>Followers of <%= @user.email %></h3>
      <ul>
        <% @user_followers.each do | user | %>
          <li> <%= link_to  user.email, following_user_path(user) %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @type.include? :following %>
    <div class="col-4">
      <h3><%= @user.email %> Following</h3>
      <ul>
        <% @user_following.each do | user | %>
          <li> <%= link_to  user.email, followers_user_path(user) %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-4">
    <h3>Tweets of <%= @user.email %></h3>
    <ul class="tweets">
      <% @user.tweets.reverse.each do | tweet | %>
        <li class="tweet">
          <div class="font-10">Tweet Time - <%= tweet.created_at%></div>
          <%= tweet.tweet %>
        </li>
      <% end %>
    </ul>
  </div>
</div>